import CreatureStack from './CreatureStack'
import RandomGenerator from 'utils/RandomGenerator'

let models = {
  infernalTroglodyte: {
    attack: 5,
    defence: 4,
    damage: {
      min: 1,
      max: 3
    },
    health: 6,
    speed: 5
  },
  pixie: {
    attack: 2,
    defence: 2,
    damage: {
      min: 1,
      max: 2
    },
    health: 3,
    speed: 7
  }
}

let random = new RandomGenerator()

describe('CreatureStack', () => {
  describe('hit()', () => {
    it('should give similar results to original VCMI implementation', () => {
      let tests = [
        {
          attacker: 4,
          defender: 19,
          results: [
            7,
            6,
            8,
            12,
            9,
            7,
            11,
            9,
            9,
            8,
            7,
            9,
            7,
            6,
            7,
            7,
            10,
            10,
            12,
            7,
            8,
            5,
            8,
            9,
            7,
            8,
            7,
            8,
            8,
            8,
            8,
            6,
            8,
            9,
            9,
            8,
            8,
            7,
            8,
            7,
            8,
            8,
            8,
            8,
            6,
            7,
            7,
            6,
            9,
            10,
            5,
            10,
            11,
            8,
            7,
            9,
            7,
            8,
            9,
            9,
            6,
            7,
            9,
            7,
            9,
            7,
            7,
            7,
            9,
            10,
            6,
            8,
            6,
            9,
            7,
            6,
            10,
            9,
            9,
            10,
            11,
            9,
            10,
            6,
            10,
            9,
            8,
            6,
            8,
            9,
            9,
            10,
            9,
            6,
            8,
            11,
            8,
            8,
            5,
            9
          ]
        },
        {
          attacker: 4,
          defender: 17,
          results: [
            6,
            9,
            9,
            11,
            5,
            10,
            8,
            9,
            7,
            7,
            9,
            9,
            8,
            5,
            7,
            9,
            7,
            10,
            5,
            10,
            9,
            6,
            8,
            7,
            8,
            6,
            7,
            9,
            9,
            10,
            7,
            10,
            9,
            8,
            5,
            8,
            6,
            5,
            7,
            7,
            10,
            6,
            11,
            9,
            10,
            8,
            8,
            9,
            11,
            8,
            7,
            9,
            7,
            7,
            8,
            10,
            10,
            7,
            11,
            8,
            7,
            6,
            9,
            5,
            10,
            7,
            6,
            7,
            8,
            12,
            11,
            9,
            8,
            9,
            8,
            6,
            7,
            6,
            8,
            8,
            10,
            7,
            8,
            9,
            9,
            8,
            11,
            9,
            8,
            8,
            8,
            9,
            9,
            11,
            8,
            9,
            8,
            10,
            7,
            10
          ]
        },
        {
          attacker: 4,
          defender: 13,
          results: [
            9,
            8,
            7,
            9,
            8,
            7,
            11,
            7,
            10,
            10,
            12,
            8,
            7,
            7,
            7,
            7,
            9,
            8,
            8,
            12,
            10,
            7,
            9,
            7,
            8,
            11,
            7,
            6,
            11,
            11,
            8,
            8,
            11,
            9,
            8,
            8,
            6,
            9,
            9,
            9,
            10,
            7,
            10,
            7,
            8,
            9,
            7,
            10,
            9,
            6,
            9,
            10,
            8,
            9,
            7,
            7,
            9,
            6,
            10,
            10,
            7,
            9,
            8,
            9,
            8,
            9,
            8,
            9,
            9,
            8,
            10,
            7,
            9,
            8,
            7,
            8,
            10,
            6,
            5,
            6,
            8,
            10,
            6,
            9,
            7,
            7,
            9,
            7,
            9,
            8,
            7,
            5,
            8,
            11,
            11,
            7,
            9,
            6,
            7,
            6
          ]
        },
        {
          attacker: 3,
          defender: 10,
          results: [
            6,
            8,
            6,
            7,
            6,
            5,
            6,
            5,
            4,
            6,
            4,
            7,
            4,
            6,
            7,
            5,
            6,
            6,
            6,
            7,
            4,
            5,
            5,
            6,
            7,
            4,
            6,
            5,
            7,
            5,
            4,
            5,
            6,
            7,
            4,
            8,
            5,
            7,
            7,
            8,
            6,
            5,
            7,
            5,
            5,
            5,
            4,
            5,
            7,
            6,
            5,
            4,
            6,
            4,
            8,
            5,
            5,
            6,
            5,
            5,
            6,
            5,
            6,
            5,
            6,
            3,
            5,
            8,
            3,
            6,
            7,
            8,
            5,
            5,
            6,
            4,
            5,
            7,
            4,
            6,
            5,
            7,
            4,
            6,
            6,
            6,
            8,
            7,
            8,
            6,
            5,
            5,
            6,
            6,
            5,
            4,
            6,
            5,
            5,
            5
          ]
        },
        {
          attacker: 1,
          defender: 8,
          results: [
            1,
            2,
            1,
            2,
            3,
            2,
            2,
            1,
            2,
            2,
            2,
            1,
            1,
            2,
            1,
            2,
            2,
            2,
            1,
            3,
            2,
            1,
            3,
            1,
            3,
            2,
            3,
            2,
            1,
            2,
            2,
            3,
            3,
            1,
            1,
            3,
            3,
            3,
            2,
            2,
            1,
            2,
            2,
            1,
            2,
            3,
            1,
            1,
            1,
            1,
            2,
            3,
            2,
            1,
            1,
            3,
            2,
            1,
            2,
            1,
            2,
            2,
            2,
            1,
            3,
            1,
            3,
            3,
            1,
            3,
            1,
            1,
            3,
            2,
            2,
            2,
            3,
            3,
            3,
            1,
            3,
            1,
            2,
            2,
            3,
            2,
            3,
            2,
            1,
            2,
            1,
            2,
            2,
            3,
            2,
            3,
            2,
            2,
            2,
            2
          ]
        },
        {
          attacker: 4,
          defender: 8,
          results: [
            10,
            9,
            8,
            7,
            10,
            7,
            7,
            9,
            9,
            8,
            9,
            7,
            9,
            8,
            7,
            6,
            8,
            8,
            8,
            10,
            10,
            7,
            9,
            6,
            5,
            8,
            8,
            9,
            8,
            10,
            8,
            10,
            6,
            9,
            10,
            6,
            5,
            8,
            7,
            9,
            9,
            6,
            8,
            7,
            9,
            8,
            7,
            7,
            8,
            7,
            10,
            8,
            7,
            7,
            9,
            10,
            5,
            9,
            9,
            8,
            11,
            8,
            10,
            7,
            9,
            9,
            8,
            7,
            7,
            8,
            9,
            8,
            8,
            8,
            11,
            8,
            8,
            7,
            9,
            10,
            9,
            7,
            8,
            8,
            8,
            9,
            8,
            9,
            9,
            9,
            11,
            8,
            7,
            7,
            8,
            6,
            7,
            8,
            9,
            10
          ]
        },
        {
          attacker: 4,
          defender: 4,
          results: [
            10,
            9,
            9,
            9,
            9,
            10,
            7,
            10,
            5,
            8,
            7,
            6,
            9,
            8,
            8,
            10,
            8,
            5,
            7,
            10,
            7,
            8,
            7,
            8,
            9,
            8,
            5,
            8,
            7,
            6,
            9,
            7,
            8,
            8,
            9,
            8,
            9,
            6,
            8,
            8,
            8,
            9,
            7,
            9,
            7,
            7,
            7,
            8,
            9,
            9,
            8,
            9,
            10,
            8,
            8,
            6,
            9,
            8,
            8,
            9,
            7,
            8,
            10,
            9,
            8,
            8,
            10,
            6,
            7,
            7,
            8,
            8,
            6,
            9,
            7,
            9,
            11,
            7,
            6,
            6,
            7,
            9,
            8,
            7,
            7,
            10,
            6,
            8,
            8,
            10,
            9,
            11,
            7,
            7,
            10,
            8,
            9,
            11,
            10,
            9
          ]
        },
        {
          attacker: 3,
          defender: 2,
          results: [
            7,
            5,
            7,
            6,
            5,
            7,
            5,
            7,
            6,
            6,
            6,
            7,
            6,
            5,
            7,
            6,
            6,
            6,
            5,
            7,
            7,
            6,
            5,
            6,
            6,
            5,
            7,
            7,
            5,
            6,
            6,
            4,
            6,
            5,
            6,
            4,
            4,
            8,
            6,
            5,
            6,
            5,
            4,
            4,
            4,
            5,
            5,
            4,
            6,
            5,
            6,
            8,
            6,
            5,
            8,
            5,
            5,
            6,
            5,
            7,
            6,
            5,
            3,
            6,
            5,
            4,
            5,
            6,
            5,
            7,
            5,
            7,
            4,
            6,
            5,
            6,
            5,
            6,
            6,
            8,
            6,
            5,
            7,
            5,
            5,
            6,
            6,
            8,
            7,
            5,
            4,
            6,
            6,
            7,
            7,
            5,
            7,
            5,
            6,
            7
          ]
        }
      ]

      let getMedian = array => {
        if (!array.length) {
          return 0
        }
        var numbers = array.slice(0).sort((a, b) => a - b)
        var middle = Math.floor(numbers.length / 2)
        var isEven = numbers.length % 2 === 0
        return isEven
          ? (numbers[middle] + numbers[middle - 1]) / 2
          : numbers[middle]
      }

      let getAvg = array => {
        return (
          array.reduce(function(p, c) {
            return p + c
          }) / array.length
        )
      }

      let getResultsInfo = array => {
        let result = {
          min: Math.min(...array),
          max: Math.max(...array),
          median: getMedian(array),
          average: getAvg(array)
        }
        return result
      }

      let compareInfo = (info1, info2) => {
        let result = {
          minDiff: info2.min - info1.min,
          maxDiff: info1.max - info2.max,
          medDiff: Math.abs(info1.median - info2.median),
          avrDiff: Math.abs(info1.average - info2.average)
        }
        let totalDiff = 0
        for (let key in result) {
          totalDiff += Math.abs(result[key])
        }
        result.totalDiff = totalDiff
        return result
      }

      let sumDiff = 0
      let minusDiff = 0
      for (let test of tests) {
        let originalInfo = getResultsInfo(test.results)
        let newResults = []
        for (let i = 0; i < test.results.length; i++) {
          let attacker = new CreatureStack({
            model: models.infernalTroglodyte,
            amount: test.attacker,
            random
          })

          let defender = new CreatureStack({
            model: { ...models.pixie, defence: 3 },
            amount: test.defender,
            random
          })

          let damage = attacker.hit(defender)
          newResults.push(damage)
        }

        let newInfo = getResultsInfo(newResults)
        let cmprInfo = compareInfo(originalInfo, newInfo)
        if (cmprInfo.minDiff < 0) {
          minusDiff += cmprInfo.minDiff
        }
        if (cmprInfo.maxDiff < 0) {
          minusDiff += cmprInfo.maxDiff
        }
        sumDiff += cmprInfo.totalDiff
      }
      let averageDiff = sumDiff / tests.length
      let averageMinusDiff = minusDiff / tests.length
      expect(averageMinusDiff).toBeLessThan(2)
      expect(averageDiff).toBeLessThan(4)
    })
  })
})
